### ISSUE TITLE
WIP branch

### ISSUE THREAD

**Issue by jonsmirl** [MitchBradley/cforth#100]
Starting from the WIP branch I have everything building inside the CForth tree on ESP IDF 4.4. However, this was a bad idea because I had to disable 90% of the added Espressif API calls.  The API signature of many calls has changed between 3.x and 4.x. In general they  switched to a model of using pointer parameters to return results and dedicating the function return value to error codes. That switch was a change for the better since the 3.x APIs were pretty random and now the 4.x APIs all have a consistent behavior.

So I am going to toss my efforts at making the WIP branch work and redo them on the cforth master. So Jos, that means you will have to redo all of your functions for IDF 4.4. That is not hard to do, but you are also going to need to either change the source of your own app to match the API changes or make new wrappers.

**Comment by jonsmirl** [comment]
Here are the changes I made to use IDF 4.x. This is not tested much, but now I can get a prompt on the esp32s3.  Should work for all esp chips now. You need to load the IDF environment first: esp-idf/export.sh
https://github.com/Lowpan-com/cforth/commit/e739b89e5e7fc7987a40aa0ffd0acfa5478e0014

So my strategy is to now add the APIs I need into extend.c, interface.h, interface.c and compile them inside cforth. Doing that generates the rodict. Then I copy all of the required forth source into my much larger app giving me a scripting language. Hopefully I will quickly stabilize on a set of needed words so that I can stop copying between the projects.

What would make embedding easier? First copying all of the need files into sdk_build and then only build using the ESP IDF (I am already doing that in my project). Second, a single command line program which processes extend.c and outputs dict.h. The current method uses  multiple programs and needs other fth files at specific paths. Could all of these pieces be combined into a single program that would be easy to add to an external build (ie a host app with forth embedded inside of it)? Then I'd have my make system generate dict.h as needed.

**Comment by Jos-Ven** [comment]
Jon wrote> So Jos, that means you will have to redo all of your 
functions for IDF 4.4
Under Win32Forth we also had to redo a number of functions again.
Most important is easy access to the operating system.
Cforth is the best Forth system of all the Forth systems I have seen for 
the ESP32 and ESP8266.
I also need at least a working PWM on my boards.

Op 16-3-2023 om 15:28 schreef Jon Smirl:
