### ISSUE TITLE
file-size not standard complian

### ISSUE THREAD

**Issue by ellerh** [MitchBradley/cforth#17]
The stack effect of `file-size` should be `( fileid -- ud ior )` but according to the comment
in forth.c it's `/* fid -- size */`

**Comment by MitchBradley** [comment]
Fixed by https://github.com/MitchBradley/cforth/commit/5ab6224c41699d2e45dd0ceb4f21f1e184be7f06

**Comment by ellerh** [comment]
Thanks!
