### ISSUE TITLE
signal handling

### ISSUE THREAD

**Issue by andrewtholt** [MitchBradley/cforth#85]
I am using a network connection (socket)

I occasionally have issue and the SIGPIPE signal is received.

Is there a mechanism in cforth for handling this signal ?

Thanks,
Andrew

**Comment by MitchBradley** [comment]
You could modify src/cforth/main.c to add SIGPIPE to the list of signals that are  handled cleanly.

**Comment by andrewtholt** [comment]
I did that, works nicely.  Thanks.
